apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '3000'
    spec:
      containers:
      - name: myapp
        image: rg.fr-par.scw.cloud/learn_k8s_rrullo_staging/app:0.2.0
      imagePullSecrets:
        - name: registry-secret