apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
    name: test
spec:
    refreshInterval: 20s
    secretStoreRef:
        kind: SecretStore
        name: secret-store
    data:
      - secretKey: test
        remoteRef:
          key: id:ID_DU_SECRET
          version: latest_enabled
